### ISSUE TITLE
OS Support

### ISSUE THREAD

**Issue by johnroper100** [LeMarck/native-popup#1]
Does this work on Windows and linux? I was trying to test on linux but got this issue: 
```
/files/Documents/test/node_modules/native-popup/index.js:43
        left: Math.max(0, (window.outerWidth - options.width) / 2) + window.screenX,
                           ^

ReferenceError: window is not defined
    at configure (/files/Documents/test/node_modules/native-popup/index.js:43:28)
    at new NativePopup (/files/Documents/test/node_modules/native-popup/index.js:122:19)
    at Object.<anonymous> (/files/Documents/test/index.js:16:15)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:760:12)
    at startup (internal/bootstrap/node.js:308:19)

```

**Comment by LeMarck** [comment]
Hi, John!

I apologize if I misled you with such a minimalistic description of the library. I fixed that, hopefully.🙂
This library is designed to **browser** (for Client JS bundle).

For example:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Test</title>
</head>
<body>
    <button id="button">Click me</button>
    <script src="node_modules/native-popup/index.js"></script>
    <script>
        const button = document.getElementById('button');
        const myPopup = new NativePopup('Popup Window');

        button.addEventListener('click', () => {
            myPopup.open('https://...').then(console.log, console.error)
        });
    </script>
</body>
</html>
```
